# Generated by Django 5.2.8 on 2025-12-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código de Barras'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Sin Marca', max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PERFUME', 'Perfume'), ('EDT', 'Eau de Toilette'), ('EDC', 'Eau de Cologne'), ('EDP', 'Eau de Parfum'), ('BODY_SPRAY', 'Body Spray'), ('LOTION', 'Loción Corporal'), ('CREAM', 'Crema'), ('GEL', 'Gel'), ('DEODORANT', 'Desodorante'), ('OTHER', 'Otro')], default='OTHER', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de adquisición', max_digits=10, verbose_name='Costo'),
        ),
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AddField(
            model_name='product',
            name='fragrance_type',
            field=models.CharField(blank=True, choices=[('FLORAL', 'Floral'), ('ORIENTAL', 'Oriental'), ('WOODY', 'Amaderado'), ('FRESH', 'Fresco'), ('CITRUS', 'Cítrico'), ('FRUITY', 'Frutal'), ('SPICY', 'Especiado'), ('AQUATIC', 'Acuático'), ('GOURMAND', 'Gourmand'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Fragancia'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('U', 'Unisex')], default='U', max_length=1, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.IntegerField(default=5, help_text='Alerta cuando el stock sea menor o igual a este valor', verbose_name='Stock Mínimo'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.IntegerField(default=100, help_text='Volumen en mililitros', verbose_name='Volumen (ml)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(verbose_name='Cantidad en Stock'),
        ),
    ]
