# Generated by Django 5.2.8 on 2025-12-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('USER', 'Usuario'), ('SELLER', 'Vendedor'), ('ADMIN', 'Administrador')], default='USER', max_length=10, verbose_name='Rol'),
        ),
    ]
