# Generated by Django 5.2.8 on 2025-12-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiration_date',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SELLER', 'Vendedor'), ('ADMIN', 'Administrador')], default='SELLER', max_length=10, verbose_name='Rol'),
        ),
    ]
