# Generated by Django 5.2.8 on 2025-12-08 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de adquisición', max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El costo no puede ser negativo')], verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.IntegerField(default=5, help_text='Alerta cuando el stock sea menor o igual a este valor', validators=[django.core.validators.MinValueValidator(0, message='El stock mínimo no puede ser negativo')], verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El precio no puede ser negativo')], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='La cantidad no puede ser negativa')], verbose_name='Cantidad en Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.IntegerField(default=100, help_text='Volumen en mililitros', validators=[django.core.validators.MinValueValidator(1, message='El volumen debe ser mayor a 0')], verbose_name='Volumen (ml)'),
        ),
    ]
